/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;

import cci.MainControl;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Bernardo
 */
public class AddQuestionDialog extends javax.swing.JDialog {

    MainControl mainControl;
    /**
     * Creates new form AddQuestionDialog
     * @param parent
     * @param modal
     */
    public AddQuestionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        escapeKeyStroke();
    }
    
    public AddQuestionDialog(java.awt.Frame parent, boolean modal, MainControl mainControl) {
        super(parent, modal);
        this.mainControl = mainControl;
        initComponents();
        
        escapeKeyStroke();
    }

    
    public void warningQuestionLabelEventOpen(){
        warningQuestionLabel.setVisible(true);
        this.pack();
    }
    public void warningQuestionLabelEventClose(){
        warningQuestionLabel.setVisible(false);
        this.pack();
    }
    
    void isOk(){
        if(!questionTextArea.getText().trim().isEmpty() 
                && !correctAnswerTextField.getText().trim().isEmpty() 
                && !wrongAnswer1TextField.getText().trim().isEmpty() 
                && !wrongAnswer2TextField.getText().trim().isEmpty() 
                && !wrongAnswer3TextField.getText().trim().isEmpty())
            addQuestionButton.setEnabled(true);
        
        else 
            addQuestionButton.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionTextArea = new javax.swing.JTextArea();
        correctLabel = new javax.swing.JLabel();
        correctAnswerTextField = new javax.swing.JTextField();
        wrongAnswer1Label = new javax.swing.JLabel();
        wrongAnswer1TextField = new javax.swing.JTextField();
        wrongAnswer2Label = new javax.swing.JLabel();
        wrongAnswer2TextField = new javax.swing.JTextField();
        wrongAnswer3Label = new javax.swing.JLabel();
        wrongAnswer3TextField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        levelLabel = new javax.swing.JLabel();
        levelComboBox = new javax.swing.JComboBox();
        addQuestionButton = new javax.swing.JButton();
        addQuestionButton.setEnabled(false);
        cancelButton = new javax.swing.JButton();
        warningQuestionLabel = new javax.swing.JLabel();
        warningQuestionLabel.setVisible(false);
        warningCorrectLabel = new javax.swing.JLabel();
        warningCorrectLabel.setVisible(false);
        warningWrongLabel = new javax.swing.JLabel();
        warningWrongLabel.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        questionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        questionLabel.setText("Question:");

        questionTextArea.setColumns(20);
        questionTextArea.setLineWrap(true);
        questionTextArea.setRows(5);
        questionTextArea.setWrapStyleWord(true);
        questionTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                questionTextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(questionTextArea);

        correctLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        correctLabel.setText("Correct Answer:");

        correctAnswerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                correctAnswerTextFieldKeyReleased(evt);
            }
        });

        wrongAnswer1Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        wrongAnswer1Label.setText("Wrong Answer 1:");

        wrongAnswer1TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wrongAnswer1TextFieldKeyReleased(evt);
            }
        });

        wrongAnswer2Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        wrongAnswer2Label.setText("Wrong Answer 2:");

        wrongAnswer2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wrongAnswer2TextFieldKeyReleased(evt);
            }
        });

        wrongAnswer3Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        wrongAnswer3Label.setText("Wrong Answer 3:");

        wrongAnswer3TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wrongAnswer3TextFieldKeyReleased(evt);
            }
        });

        categoryLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        categoryLabel.setText("Category :");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Culture", "Sport", "Geography", "History", "Science" }));

        levelLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        levelLabel.setText("Level :");

        levelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Easy", "Medium", "Hard" }));

        addQuestionButton.setText("Add Question");
        addQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestionButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        warningQuestionLabel.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        warningQuestionLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningQuestionLabel.setText("Question already registered.");

        warningCorrectLabel.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        warningCorrectLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningCorrectLabel.setText("There must be a correct answer.");

        warningWrongLabel.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        warningWrongLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningWrongLabel.setText("Missing Wrong answer(s).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addQuestionButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(questionLabel)
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(wrongAnswer1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wrongAnswer1TextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(wrongAnswer2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wrongAnswer2TextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(correctLabel)
                        .addGap(12, 12, 12)
                        .addComponent(correctAnswerTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wrongAnswer3Label)
                            .addComponent(categoryLabel)
                            .addComponent(levelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wrongAnswer3TextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warningQuestionLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(warningCorrectLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(warningWrongLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningQuestionLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctLabel)
                    .addComponent(correctAnswerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningCorrectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrongAnswer1Label)
                    .addComponent(wrongAnswer1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrongAnswer2Label)
                    .addComponent(wrongAnswer2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningWrongLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrongAnswer3Label)
                    .addComponent(wrongAnswer3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addQuestionButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestionButtonActionPerformed
        
        ArrayList<String> answers = new ArrayList<>();
        answers.add(correctAnswerTextField.getText().trim());
        answers.add(wrongAnswer1TextField.getText().trim());
        answers.add(wrongAnswer2TextField.getText().trim());
        answers.add(wrongAnswer3TextField.getText().trim());
        
        this.mainControl.addQuestion(categoryComboBox.getSelectedItem(),levelComboBox.getSelectedItem(),
                questionTextArea.getText().trim(),answers);
        this.dispose();
    }//GEN-LAST:event_addQuestionButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void questionTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_questionTextAreaKeyReleased
        isOk();
    }//GEN-LAST:event_questionTextAreaKeyReleased

    private void correctAnswerTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correctAnswerTextFieldKeyReleased
        isOk();
    }//GEN-LAST:event_correctAnswerTextFieldKeyReleased

    private void wrongAnswer1TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wrongAnswer1TextFieldKeyReleased
        isOk();
    }//GEN-LAST:event_wrongAnswer1TextFieldKeyReleased

    private void wrongAnswer2TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wrongAnswer2TextFieldKeyReleased
        isOk();
    }//GEN-LAST:event_wrongAnswer2TextFieldKeyReleased

    private void wrongAnswer3TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wrongAnswer3TextFieldKeyReleased
        isOk();
    }//GEN-LAST:event_wrongAnswer3TextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddQuestionDialog dialog = new AddQuestionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void escapeKeyStroke(){
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action escapeAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cancelButtonActionPerformed(e);
            }
        }; 
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQuestionButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField correctAnswerTextField;
    private javax.swing.JLabel correctLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox levelComboBox;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JTextArea questionTextArea;
    private javax.swing.JLabel warningCorrectLabel;
    private javax.swing.JLabel warningQuestionLabel;
    private javax.swing.JLabel warningWrongLabel;
    private javax.swing.JLabel wrongAnswer1Label;
    private javax.swing.JTextField wrongAnswer1TextField;
    private javax.swing.JLabel wrongAnswer2Label;
    private javax.swing.JTextField wrongAnswer2TextField;
    private javax.swing.JLabel wrongAnswer3Label;
    private javax.swing.JTextField wrongAnswer3TextField;
    // End of variables declaration//GEN-END:variables
}
