/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;

import cci.MainControl;

/**
 *
 * @author Bernardo
 */
public class MainFrame extends javax.swing.JFrame {

    private MainControl mainControl;
    /**
     * Creates new form MainFrame1
     */
    public MainFrame() {
        initComponents();
    }
    public MainFrame(MainControl MainControl) {
        this.mainControl = MainControl;
        initComponents();
    }
    
    public void setUserNameLabel(String name){
        userNameLabel.setText(name);
        this.pack();
    }
    
    public void setQuestionsLogButton(){
        questionsLogButton.setVisible(true);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        manageAccButton = new javax.swing.JButton();
        rankingButton = new javax.swing.JButton();
        gameOptionsPanel = new javax.swing.JPanel();
        levelLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        numberOfQuestionsLabel = new javax.swing.JLabel();
        levelBox = new javax.swing.JComboBox();
        categoryBox = new javax.swing.JComboBox();
        numberOfQuestionsBox = new javax.swing.JComboBox();
        playButton = new javax.swing.JButton();
        questionsLogButton = new javax.swing.JButton();
        questionsLogButton.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        userNameLabel.setText("User Name");

        manageAccButton.setText("Manage Acc");
        manageAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccButtonActionPerformed(evt);
            }
        });

        rankingButton.setText("Ranking");
        rankingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingButtonActionPerformed(evt);
            }
        });

        gameOptionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Game Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 10), java.awt.Color.white), "Game Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 12), java.awt.Color.darkGray)); // NOI18N

        levelLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        levelLabel.setText("Select Game Level:");

        categoryLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        categoryLabel.setText("Select Category:");

        numberOfQuestionsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        numberOfQuestionsLabel.setText("Number of Questions:");

        levelBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Easy", "Medium", "Hard" }));

        categoryBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Culture", "Sport", "Geography", "History", "Science" }));

        numberOfQuestionsBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "15" }));

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameOptionsPanelLayout = new javax.swing.GroupLayout(gameOptionsPanel);
        gameOptionsPanel.setLayout(gameOptionsPanelLayout);
        gameOptionsPanelLayout.setHorizontalGroup(
            gameOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameOptionsPanelLayout.createSequentialGroup()
                        .addComponent(numberOfQuestionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfQuestionsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameOptionsPanelLayout.createSequentialGroup()
                        .addGroup(gameOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(levelLabel)
                            .addComponent(categoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gameOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameOptionsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(playButton))
        );
        gameOptionsPanelLayout.setVerticalGroup(
            gameOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(levelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfQuestionsLabel)
                    .addComponent(numberOfQuestionsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playButton)
                .addContainerGap())
        );

        questionsLogButton.setText("Questions log");
        questionsLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionsLogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameLabel)
                    .addComponent(manageAccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionsLogButton)
                    .addComponent(rankingButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageAccButton)
                        .addGap(41, 41, 41)
                        .addComponent(questionsLogButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rankingButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rankingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingButtonActionPerformed
        mainControl.rankingFrameOpen();
    }//GEN-LAST:event_rankingButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        mainControl.playDialogOpen(levelBox.getSelectedItem(),categoryBox.getSelectedItem(),
                numberOfQuestionsBox.getSelectedItem());
    }//GEN-LAST:event_playButtonActionPerformed

    private void manageAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccButtonActionPerformed
        mainControl.manageAccDialogOpen();
    }//GEN-LAST:event_manageAccButtonActionPerformed

    private void questionsLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionsLogButtonActionPerformed
        mainControl.questionLogOpen();
    }//GEN-LAST:event_questionsLogButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox categoryBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JPanel gameOptionsPanel;
    private javax.swing.JComboBox levelBox;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton manageAccButton;
    private javax.swing.JComboBox numberOfQuestionsBox;
    private javax.swing.JLabel numberOfQuestionsLabel;
    private javax.swing.JButton playButton;
    private javax.swing.JButton questionsLogButton;
    private javax.swing.JButton rankingButton;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
