/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;

import cci.MainControl;
import cln.cdp.Participant;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author Bernardo
 */
public final class ManageAccDialog extends javax.swing.JDialog {

    private MainControl mainControl;

    /**
     * Creates new form ManageAccDialog
     *
     * @param parent
     * @param modal
     */
    public ManageAccDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
    }

    public ManageAccDialog(java.awt.Frame parent, boolean modal, 
            MainControl mainControl, Participant participant, String[] allUsernames) {
        super(parent, modal);
        initComponents();
        
        if(!participant.isAdmin())
            this.tabbedPane.remove(4);
        
        this.mainControl = mainControl;
        currentUsernameLabel.setText(participant.getUserName());
        currentRealNameLabel.setText(participant.getRealName());
        currentEMailLabel.setText(participant.getEmail());
        
        refreshComboBox(allUsernames);
        
        AutoCompleteDecorator.decorate(this.comboBox);
        
        this.pack();
    }
    
    public void refreshComboBox(String[] allUsernames){
        comboBox.setModel(new javax.swing.DefaultComboBoxModel(allUsernames));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        namePanel = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        currentLabel = new javax.swing.JLabel();
        newLabel = new javax.swing.JLabel();
        newUsernameTextField = new javax.swing.JTextField();
        changeUsernameButton = new javax.swing.JButton();
        forSafetyLabel1 = new javax.swing.JLabel();
        forSafetyTextField1 = new javax.swing.JPasswordField();
        forSafetyTextField1.setTransferHandler(null);
        currentUsernameLabel = new javax.swing.JLabel();
        realNamePanel = new javax.swing.JPanel();
        currentLabel2 = new javax.swing.JLabel();
        currentRealNameLabel = new javax.swing.JLabel();
        newLabel2 = new javax.swing.JLabel();
        newRealNameTextField = new javax.swing.JTextField();
        changeRealNameButton = new javax.swing.JButton();
        forSafetyLabel2 = new javax.swing.JLabel();
        forSafetyTextField2 = new javax.swing.JPasswordField();
        forSafetyTextField2.setTransferHandler(null);
        pswdPanel = new javax.swing.JPanel();
        currentLabel3 = new javax.swing.JLabel();
        newLabel3 = new javax.swing.JLabel();
        reTypeLabel1 = new javax.swing.JLabel();
        changePswdButton = new javax.swing.JButton();
        currentPswdTextField = new javax.swing.JPasswordField();
        currentPswdTextField.setTransferHandler(null);
        newPswdTextField = new javax.swing.JPasswordField();
        newPswdTextField.setTransferHandler(null);
        reTypeNewPswdTextField = new javax.swing.JPasswordField();
        reTypeNewPswdTextField.setTransferHandler(null);
        mismatchingPswdLabel = new javax.swing.JLabel();
        mismatchingPswdLabel.setVisible(false);
        eMailPanel = new javax.swing.JPanel();
        currentLabel4 = new javax.swing.JLabel();
        currentEMailLabel = new javax.swing.JLabel();
        newLabel4 = new javax.swing.JLabel();
        newEMailTextField = new javax.swing.JTextField();
        reTypeLabel2 = new javax.swing.JLabel();
        reTypeNewEMailTextField = new javax.swing.JTextField();
        reTypeNewEMailTextField.setTransferHandler(null);
        changeEMailButton = new javax.swing.JButton();
        forSafetyLabel3 = new javax.swing.JLabel();
        forSafetyTextField3 = new javax.swing.JPasswordField();
        forSafetyTextField3.setTransferHandler(null);
        deletePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        forSafetyTextField6 = new javax.swing.JPasswordField();
        forSafetyTextField6.setTransferHandler(null);
        forSafetyLabel6 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        deleteUserPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        deleteUserButton = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox();
        forSafetyLabel5 = new javax.swing.JLabel();
        forSafetyTextField5 = new javax.swing.JPasswordField();
        forSafetyTextField5.setTransferHandler(null);
        turnIntoAdmin = new javax.swing.JPanel();
        usernameLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        turnIntoAdminButton = new javax.swing.JButton();
        forSafetyLabel4 = new javax.swing.JLabel();
        forSafetyTextField4 = new javax.swing.JPasswordField();
        forSafetyTextField4.setTransferHandler(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabbedPane.setToolTipText("");

        usernamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 14), java.awt.Color.black)); // NOI18N

        currentLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        currentLabel.setText("Current Username:");

        newLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newLabel.setText("New Username:");

        newUsernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newUsernameTextFieldKeyReleased(evt);
            }
        });

        changeUsernameButton.setText("Change");
        changeUsernameButton.setEnabled(false);
        changeUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUsernameButtonActionPerformed(evt);
            }
        });

        forSafetyLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        forSafetyLabel1.setText("For safety, confirm your password:");

        currentUsernameLabel.setText("currentUsernameLabel");

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usernamePanelLayout.createSequentialGroup()
                        .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentLabel)
                            .addComponent(newLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newUsernameTextField)
                            .addGroup(usernamePanelLayout.createSequentialGroup()
                                .addComponent(currentUsernameLabel)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(usernamePanelLayout.createSequentialGroup()
                        .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(usernamePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(forSafetyTextField1))
                            .addComponent(forSafetyLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeUsernameButton)))
                .addContainerGap())
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentLabel)
                    .addComponent(currentUsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLabel)
                    .addComponent(newUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forSafetyLabel1)
                .addGroup(usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usernamePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(changeUsernameButton)
                        .addContainerGap())
                    .addGroup(usernamePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forSafetyTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        realNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change Real Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 14), java.awt.Color.black)); // NOI18N

        currentLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        currentLabel2.setText("Current Real Name:");

        currentRealNameLabel.setText("jLabel5");

        newLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newLabel2.setText("New Real Name:");

        newRealNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newRealNameTextFieldKeyReleased(evt);
            }
        });

        changeRealNameButton.setText("Change");
        changeRealNameButton.setEnabled(false);
        changeRealNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeRealNameButtonActionPerformed(evt);
            }
        });

        forSafetyLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        forSafetyLabel2.setText("For safety, confirm your password:");

        javax.swing.GroupLayout realNamePanelLayout = new javax.swing.GroupLayout(realNamePanel);
        realNamePanel.setLayout(realNamePanelLayout);
        realNamePanelLayout.setHorizontalGroup(
            realNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(realNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(realNamePanelLayout.createSequentialGroup()
                        .addGroup(realNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentLabel2)
                            .addComponent(newLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(realNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentRealNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newRealNameTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, realNamePanelLayout.createSequentialGroup()
                        .addGroup(realNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(forSafetyLabel2)
                            .addGroup(realNamePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(forSafetyTextField2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(changeRealNameButton)))
                .addContainerGap())
        );
        realNamePanelLayout.setVerticalGroup(
            realNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(realNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentLabel2)
                    .addComponent(currentRealNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(realNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLabel2)
                    .addComponent(newRealNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(realNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(realNamePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeRealNameButton)
                        .addContainerGap())
                    .addGroup(realNamePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forSafetyLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forSafetyTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(realNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(realNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Name", namePanel);

        currentLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        currentLabel3.setText("Current password:");

        newLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newLabel3.setText("New password:");

        reTypeLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reTypeLabel1.setText("Re-type:");

        changePswdButton.setText("Change");
        changePswdButton.setEnabled(false);
        changePswdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePswdButtonActionPerformed(evt);
            }
        });

        newPswdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newPswdTextFieldKeyReleased(evt);
            }
        });

        reTypeNewPswdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reTypeNewPswdTextFieldKeyReleased(evt);
            }
        });

        mismatchingPswdLabel.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        mismatchingPswdLabel.setForeground(new java.awt.Color(255, 0, 0));
        mismatchingPswdLabel.setText("Mismatching passwords.");

        javax.swing.GroupLayout pswdPanelLayout = new javax.swing.GroupLayout(pswdPanel);
        pswdPanel.setLayout(pswdPanelLayout);
        pswdPanelLayout.setHorizontalGroup(
            pswdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pswdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pswdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pswdPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(changePswdButton))
                    .addGroup(pswdPanelLayout.createSequentialGroup()
                        .addComponent(reTypeLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(reTypeNewPswdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                    .addGroup(pswdPanelLayout.createSequentialGroup()
                        .addComponent(currentLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentPswdTextField))
                    .addGroup(pswdPanelLayout.createSequentialGroup()
                        .addComponent(newLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(newPswdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                    .addGroup(pswdPanelLayout.createSequentialGroup()
                        .addComponent(mismatchingPswdLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pswdPanelLayout.setVerticalGroup(
            pswdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pswdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pswdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentLabel3)
                    .addComponent(currentPswdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pswdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLabel3)
                    .addComponent(newPswdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pswdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reTypeLabel1)
                    .addComponent(reTypeNewPswdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changePswdButton)
                .addGap(18, 18, 18)
                .addComponent(mismatchingPswdLabel)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Password", pswdPanel);

        currentLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        currentLabel4.setText("Current E-Mail:");

        currentEMailLabel.setText("jLabel9");

        newLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        newLabel4.setText("New E-Mail:");

        newEMailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newEMailTextFieldKeyReleased(evt);
            }
        });

        reTypeLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reTypeLabel2.setText("Re-type:");

        reTypeNewEMailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reTypeNewEMailTextFieldKeyReleased(evt);
            }
        });

        changeEMailButton.setText("Change");
        changeEMailButton.setEnabled(false);
        changeEMailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEMailButtonActionPerformed(evt);
            }
        });

        forSafetyLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        forSafetyLabel3.setText("For safety, confirm your password:");

        javax.swing.GroupLayout eMailPanelLayout = new javax.swing.GroupLayout(eMailPanel);
        eMailPanel.setLayout(eMailPanelLayout);
        eMailPanelLayout.setHorizontalGroup(
            eMailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eMailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eMailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eMailPanelLayout.createSequentialGroup()
                        .addGroup(eMailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentLabel4)
                            .addComponent(newLabel4)
                            .addComponent(reTypeLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(eMailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentEMailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(newEMailTextField)
                            .addComponent(reTypeNewEMailTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eMailPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(changeEMailButton))
                    .addGroup(eMailPanelLayout.createSequentialGroup()
                        .addGroup(eMailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forSafetyTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forSafetyLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        eMailPanelLayout.setVerticalGroup(
            eMailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eMailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eMailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentLabel4)
                    .addComponent(currentEMailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eMailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLabel4)
                    .addComponent(newEMailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eMailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reTypeLabel2)
                    .addComponent(reTypeNewEMailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(forSafetyLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forSafetyTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(changeEMailButton)
                .addContainerGap())
        );

        tabbedPane.addTab("E-Mail", eMailPanel);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Delete account here:");

        forSafetyLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        forSafetyLabel6.setText("For safety, confirm your password:");

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        warningLabel.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningLabel.setText("There is no turning back!");

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forSafetyTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forSafetyLabel6)))
                    .addComponent(jLabel1))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addComponent(warningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton))
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forSafetyLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forSafetyTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(warningLabel)))
                .addContainerGap())
        );

        tabbedPane.addTab("Delete", deletePanel);

        deleteUserPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 14), java.awt.Color.black)); // NOI18N

        usernameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        usernameLabel.setText("Username:");

        deleteUserButton.setText("Change");
        deleteUserButton.setEnabled(false);
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        comboBox.setEditable(true);
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        forSafetyLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        forSafetyLabel5.setText("For safety, confirm your password:");

        javax.swing.GroupLayout deleteUserPanelLayout = new javax.swing.GroupLayout(deleteUserPanel);
        deleteUserPanel.setLayout(deleteUserPanelLayout);
        deleteUserPanelLayout.setHorizontalGroup(
            deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteUserPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteUserPanelLayout.createSequentialGroup()
                        .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forSafetyTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forSafetyLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteUserButton))
                    .addGroup(deleteUserPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );
        deleteUserPanelLayout.setVerticalGroup(
            deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteUserPanelLayout.createSequentialGroup()
                        .addComponent(deleteUserButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteUserPanelLayout.createSequentialGroup()
                        .addComponent(forSafetyLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forSafetyTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        turnIntoAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turn into Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Abadi MT Condensed Extra Bold", 1, 14), java.awt.Color.black)); // NOI18N

        usernameLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        usernameLabel1.setText("Username:");

        usernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameTextFieldKeyReleased(evt);
            }
        });

        turnIntoAdminButton.setText("Change");
        turnIntoAdminButton.setEnabled(false);
        turnIntoAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnIntoAdminButtonActionPerformed(evt);
            }
        });

        forSafetyLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        forSafetyLabel4.setText("For safety, confirm your password:");

        javax.swing.GroupLayout turnIntoAdminLayout = new javax.swing.GroupLayout(turnIntoAdmin);
        turnIntoAdmin.setLayout(turnIntoAdminLayout);
        turnIntoAdminLayout.setHorizontalGroup(
            turnIntoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(turnIntoAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(turnIntoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(turnIntoAdminLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(turnIntoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forSafetyTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forSafetyLabel4)))
                    .addGroup(turnIntoAdminLayout.createSequentialGroup()
                        .addComponent(usernameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, turnIntoAdminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(turnIntoAdminButton))
        );
        turnIntoAdminLayout.setVerticalGroup(
            turnIntoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(turnIntoAdminLayout.createSequentialGroup()
                .addGroup(turnIntoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel1)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forSafetyLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forSafetyTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(turnIntoAdminButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(turnIntoAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turnIntoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Admin", adminPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernameButtonActionPerformed
        String newCurrentUsername = this.mainControl.changeUsername(newUsernameTextField.getText(), 
                forSafetyTextField1.getText());
        if(newCurrentUsername != null){
            currentUsernameLabel.setText(newCurrentUsername);
            this.pack();
        }
            
    }//GEN-LAST:event_changeUsernameButtonActionPerformed

    private void changeRealNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeRealNameButtonActionPerformed
        String newCurrentRealName = this.mainControl.changeRealName(newRealNameTextField.getText(), forSafetyTextField2.getText());
        if(newCurrentRealName != null){
            currentRealNameLabel.setText(newCurrentRealName);
            this.pack();
        }
    }//GEN-LAST:event_changeRealNameButtonActionPerformed

    private void changePswdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePswdButtonActionPerformed
        if (newPswdTextField.getText().equals(reTypeNewPswdTextField.getText())) {
            this.mainControl.changePswd(newPswdTextField.getText(), currentPswdTextField.getText());
        }else{
            mismatchingPswdLabel.setVisible(true);
        }
    }//GEN-LAST:event_changePswdButtonActionPerformed

    private void changeEMailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEMailButtonActionPerformed
        if (newEMailTextField.getText().equals(reTypeNewEMailTextField.getText())) {
            String newCurrentEMail = this.mainControl.changeEMail(newEMailTextField.getText(), forSafetyTextField3.getText());
            if(newCurrentEMail != null){
                currentEMailLabel.setText(newCurrentEMail);
                this.pack();
            }
        } else {
            reTypeNewEMailTextField.setText("Mismatching e-mails!");
        }
    }//GEN-LAST:event_changeEMailButtonActionPerformed

    private void newPswdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPswdTextFieldKeyReleased
        mismatchingPswdLabel.setVisible(false);
        if(!newPswdTextField.getText().trim().isEmpty() && !reTypeNewPswdTextField.getText().trim().isEmpty())
            changePswdButton.setEnabled(true);
        else
            changePswdButton.setEnabled(false);
    }//GEN-LAST:event_newPswdTextFieldKeyReleased

    private void reTypeNewPswdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reTypeNewPswdTextFieldKeyReleased
        mismatchingPswdLabel.setVisible(false);
        if(!newPswdTextField.getText().trim().isEmpty() && !reTypeNewPswdTextField.getText().trim().isEmpty())
            changePswdButton.setEnabled(true);
        else
            changePswdButton.setEnabled(false);
    }//GEN-LAST:event_reTypeNewPswdTextFieldKeyReleased

    private void newUsernameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newUsernameTextFieldKeyReleased
        if(!newUsernameTextField.getText().trim().isEmpty())
            changeUsernameButton.setEnabled(true);
        else
            changeUsernameButton.setEnabled(false);
    }//GEN-LAST:event_newUsernameTextFieldKeyReleased

    private void newRealNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newRealNameTextFieldKeyReleased
        if(!newRealNameTextField.getText().trim().isEmpty())
            changeRealNameButton.setEnabled(true);
        else
            changeRealNameButton.setEnabled(false);
    }//GEN-LAST:event_newRealNameTextFieldKeyReleased

    private void newEMailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newEMailTextFieldKeyReleased
        if(!newEMailTextField.getText().trim().isEmpty() && !reTypeNewEMailTextField.getText().trim().isEmpty())
            changeEMailButton.setEnabled(true);
        else
            changeEMailButton.setEnabled(false);
    }//GEN-LAST:event_newEMailTextFieldKeyReleased

    private void reTypeNewEMailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reTypeNewEMailTextFieldKeyReleased
        if(!newEMailTextField.getText().trim().isEmpty() && !reTypeNewEMailTextField.getText().trim().isEmpty())
            changeEMailButton.setEnabled(true);
        else
            changeEMailButton.setEnabled(false);
    }//GEN-LAST:event_reTypeNewEMailTextFieldKeyReleased

    private void usernameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTextFieldKeyReleased
        if(!usernameTextField.getText().trim().isEmpty())
            turnIntoAdminButton.setEnabled(true);
        else
            turnIntoAdminButton.setEnabled(false);
    }//GEN-LAST:event_usernameTextFieldKeyReleased

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        if(comboBox.getSelectedItem() != null && !comboBox.getSelectedItem().toString().isEmpty())
            deleteUserButton.setEnabled(true);
        else
            deleteUserButton.setEnabled(false);
    }//GEN-LAST:event_comboBoxActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        mainControl.excludeUserAdmin(comboBox.getSelectedItem().toString().trim(),forSafetyTextField5.getText());
    }//GEN-LAST:event_deleteUserButtonActionPerformed

    private void turnIntoAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnIntoAdminButtonActionPerformed
        mainControl.turnInAdmin(usernameTextField.getText(), forSafetyTextField4.getText());
    }//GEN-LAST:event_turnIntoAdminButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        mainControl.excludeUserParticipant(forSafetyTextField6.getText());
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageAccDialog dialog = new ManageAccDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton changeEMailButton;
    private javax.swing.JButton changePswdButton;
    private javax.swing.JButton changeRealNameButton;
    private javax.swing.JButton changeUsernameButton;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JLabel currentEMailLabel;
    private javax.swing.JLabel currentLabel;
    private javax.swing.JLabel currentLabel2;
    private javax.swing.JLabel currentLabel3;
    private javax.swing.JLabel currentLabel4;
    private javax.swing.JPasswordField currentPswdTextField;
    private javax.swing.JLabel currentRealNameLabel;
    private javax.swing.JLabel currentUsernameLabel;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JPanel deleteUserPanel;
    private javax.swing.JPanel eMailPanel;
    private javax.swing.JLabel forSafetyLabel1;
    private javax.swing.JLabel forSafetyLabel2;
    private javax.swing.JLabel forSafetyLabel3;
    private javax.swing.JLabel forSafetyLabel4;
    private javax.swing.JLabel forSafetyLabel5;
    private javax.swing.JLabel forSafetyLabel6;
    private javax.swing.JPasswordField forSafetyTextField1;
    private javax.swing.JPasswordField forSafetyTextField2;
    private javax.swing.JPasswordField forSafetyTextField3;
    private javax.swing.JPasswordField forSafetyTextField4;
    private javax.swing.JPasswordField forSafetyTextField5;
    private javax.swing.JPasswordField forSafetyTextField6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mismatchingPswdLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JTextField newEMailTextField;
    private javax.swing.JLabel newLabel;
    private javax.swing.JLabel newLabel2;
    private javax.swing.JLabel newLabel3;
    private javax.swing.JLabel newLabel4;
    private javax.swing.JPasswordField newPswdTextField;
    private javax.swing.JTextField newRealNameTextField;
    private javax.swing.JTextField newUsernameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel pswdPanel;
    private javax.swing.JLabel reTypeLabel1;
    private javax.swing.JLabel reTypeLabel2;
    private javax.swing.JTextField reTypeNewEMailTextField;
    private javax.swing.JPasswordField reTypeNewPswdTextField;
    private javax.swing.JPanel realNamePanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel turnIntoAdmin;
    private javax.swing.JButton turnIntoAdminButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JPanel usernamePanel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
