/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cih;

import cci.EntryControl;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Bernardo
 */
public class SignUpDialog extends javax.swing.JDialog {

    private final EntryControl EntryControl;
    /**
     * Creates new form SignInDialog1
     * @param parent
     * @param modal
     */
    public SignUpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.EntryControl = null;
        initComponents();
        
        escapeKeyStroke();
    }
    
    public SignUpDialog(java.awt.Frame parent, boolean modal, EntryControl EntryControl) {
        super(parent, modal);
        this.EntryControl = EntryControl;
        initComponents();
        escapeKeyStroke();//Esc to close jDialog...
    }

    
    void warningUsernameEventOpen(){
        warningUsernameLabel.setVisible(true);
        this.pack();
    }
    void warningUsernameEventClose(){
        warningUsernameLabel.setVisible(false);
        this.pack();
    }
    void warningEMailEventOpen(boolean event){
        if(event){
            warningEMailLabel.setText("E-Mails mismatching");
            warningEMailLabel.setVisible(true);
        }else{
            warningEMailLabel.setText("E-Mail already been used");
            warningEMailLabel.setVisible(true);
        }
        this.pack();
    }
    void warningEMailEventClose(){
        warningEMailLabel.setVisible(false);
        this.pack();
    }
    void warningPswdEventOpen(){
        warningPswdLabel.setVisible(true);
        this.pack();
    }
    void warningPswdEventClose(){
        warningPswdLabel.setVisible(false);
        this.pack();
    }
    
    void isOk(){
        if(!warningPswdLabel.isVisible() 
                && !warningEMailLabel.isVisible() 
                && !warningUsernameLabel.isVisible()
                && !usernameTextField.getText().trim().isEmpty() 
                && !realNameTextField.getText().trim().isEmpty() 
                && !eMailTextField.getText().trim().isEmpty() 
                && !reEMailTextField.getText().trim().isEmpty() 
                && !pswdTextField.getText().trim().isEmpty()
                && !rePswdTextField.getText().trim().isEmpty())
            signUpButton.setEnabled(true);
        
        else 
            signUpButton.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        realNameLabel = new javax.swing.JLabel();
        eMailLabel = new javax.swing.JLabel();
        reEMailLabel = new javax.swing.JLabel();
        pswdLabel = new javax.swing.JLabel();
        rePswdLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        usernameTextField = new javax.swing.JTextField();
        realNameTextField = new javax.swing.JTextField();
        eMailTextField = new javax.swing.JTextField();
        reEMailTextField = new javax.swing.JTextField();
        reEMailTextField.setTransferHandler(null);
        warningUsernameLabel = new javax.swing.JLabel();
        warningUsernameLabel.setVisible(false);
        warningEMailLabel = new javax.swing.JLabel();
        warningEMailLabel.setVisible(false);
        warningPswdLabel = new javax.swing.JLabel();
        warningPswdLabel.setVisible(false);
        rePswdTextField = new javax.swing.JPasswordField();
        rePswdTextField.setTransferHandler(null);
        pswdTextField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        usernameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        usernameLabel.setText("Username:");

        realNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        realNameLabel.setText("Real name:");

        eMailLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        eMailLabel.setText("E-Mail:");

        reEMailLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reEMailLabel.setText("Re-type E-Mail:");

        pswdLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pswdLabel.setText("Password:");

        rePswdLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rePswdLabel.setText("Re-type password:");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        signUpButton.setText("Sign up");
        signUpButton.setEnabled(false);
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        usernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameTextFieldKeyReleased(evt);
            }
        });

        realNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                realNameTextFieldKeyReleased(evt);
            }
        });

        eMailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eMailTextFieldKeyReleased(evt);
            }
        });

        reEMailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reEMailTextFieldKeyReleased(evt);
            }
        });

        warningUsernameLabel.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        warningUsernameLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningUsernameLabel.setText("Username already been used");

        warningEMailLabel.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        warningEMailLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningEMailLabel.setText("EmailWarning");

        warningPswdLabel.setFont(new java.awt.Font("Lucida Grande", 3, 10)); // NOI18N
        warningPswdLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningPswdLabel.setText("Passwords mismatching");

        rePswdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rePswdTextFieldKeyReleased(evt);
            }
        });

        pswdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswdTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signUpButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(eMailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eMailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(reEMailLabel)
                                        .addGap(25, 25, 25)
                                        .addComponent(reEMailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(realNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(rePswdLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pswdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(rePswdTextField)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pswdLabel)
                                    .addComponent(realNameLabel)
                                    .addComponent(usernameLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warningUsernameLabel)
                            .addComponent(warningEMailLabel)
                            .addComponent(warningPswdLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningUsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realNameLabel)
                    .addComponent(realNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMailLabel)
                    .addComponent(eMailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningEMailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reEMailLabel)
                    .addComponent(reEMailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswdLabel)
                    .addComponent(warningPswdLabel)
                    .addComponent(pswdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rePswdLabel)
                    .addComponent(rePswdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(signUpButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void usernameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTextFieldKeyReleased
        warningUsernameEventClose();
        isOk();
    }//GEN-LAST:event_usernameTextFieldKeyReleased

    private void realNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_realNameTextFieldKeyReleased
        isOk();
    }//GEN-LAST:event_realNameTextFieldKeyReleased

    private void eMailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eMailTextFieldKeyReleased
        if(!eMailTextField.getText().equals(reEMailTextField.getText())){
         warningEMailEventOpen(true);
         /*if(isEMail(eMailTextField.getText()))
             warningEMailEventOpen(false);*/
        }
        else
            warningEMailEventClose();
        isOk();
    }//GEN-LAST:event_eMailTextFieldKeyReleased

    private void reEMailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reEMailTextFieldKeyReleased
        if(!eMailTextField.getText().equals(reEMailTextField.getText()))
            warningEMailEventOpen(true);
        else
            warningEMailEventClose();
        isOk();
    }//GEN-LAST:event_reEMailTextFieldKeyReleased

    private void pswdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswdTextFieldKeyReleased
        if(!pswdTextField.getText().equals(rePswdTextField.getText()))
            warningPswdEventOpen();
        else
            warningPswdEventClose();
        isOk();
    }//GEN-LAST:event_pswdTextFieldKeyReleased

    private void rePswdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rePswdTextFieldKeyReleased
        if(!pswdTextField.getText().equals(rePswdTextField.getText()))
            warningPswdEventOpen();
        else
            warningPswdEventClose();
        isOk();
    }//GEN-LAST:event_rePswdTextFieldKeyReleased

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        if(this.EntryControl.participantSignUp(usernameTextField.getText().trim(),eMailTextField.getText().trim(),
                realNameTextField.getText().trim(),pswdTextField.getText().trim())){
            EntryControl.successSignUpDialogOpen();
            this.dispose();
        }else{
            warningUsernameEventOpen();
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignUpDialog dialog = new SignUpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void escapeKeyStroke(){
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action escapeAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cancelButtonActionPerformed(e);
            }
        }; 
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel eMailLabel;
    private javax.swing.JTextField eMailTextField;
    private javax.swing.JLabel pswdLabel;
    private javax.swing.JPasswordField pswdTextField;
    private javax.swing.JLabel reEMailLabel;
    private javax.swing.JTextField reEMailTextField;
    private javax.swing.JLabel rePswdLabel;
    private javax.swing.JPasswordField rePswdTextField;
    private javax.swing.JLabel realNameLabel;
    private javax.swing.JTextField realNameTextField;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel warningEMailLabel;
    private javax.swing.JLabel warningPswdLabel;
    private javax.swing.JLabel warningUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
