make:
	gcc -c compacta.c TadLista.c TadArvore.c bitmap.c
	gcc -o compacta compacta.o TadLista.o TadArvore.o bitmap.o
	gcc -c descompacta.c TadArvore.c bitmap.c
	gcc -o descompacta descompacta.o TadArvore.o bitmap.o